-- Migration: 001_initial_schema.sql
-- Description: Sets up 'analyses' and 'fund_master' tables with RLS policies.

-- 1. Create 'analyses' table for saving User Reports
CREATE TABLE IF NOT EXISTS public.analyses (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
    funds text[] NOT NULL,
    state jsonb NOT NULL
);

-- 2. Create 'fund_master' table for AMFI AUM Data
CREATE TABLE IF NOT EXISTS public.fund_master (
    scheme_code text PRIMARY KEY,
    scheme_name text,
    aum numeric,
    updated_at timestamp with time zone DEFAULT timezone('utc'::text, now())
);

-- 3. Enable Row Level Security (RLS)
ALTER TABLE public.analyses ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.fund_master ENABLE ROW LEVEL SECURITY;

-- 4. Create Policies (Open Access for Demo - Adjust for Production)

-- Policies for 'analyses'
DROP POLICY IF EXISTS "Public read access" ON public.analyses;
CREATE POLICY "Public read access" ON public.analyses FOR SELECT USING (true);

DROP POLICY IF EXISTS "Public insert access" ON public.analyses;
CREATE POLICY "Public insert access" ON public.analyses FOR INSERT WITH CHECK (true);

-- Policies for 'fund_master'
DROP POLICY IF EXISTS "Public read access" ON public.fund_master;
CREATE POLICY "Public read access" ON public.fund_master FOR SELECT USING (true);

DROP POLICY IF EXISTS "Public insert access" ON public.fund_master;
CREATE POLICY "Public insert access" ON public.fund_master FOR INSERT WITH CHECK (true);

DROP POLICY IF EXISTS "Public update access" ON public.fund_master;
CREATE POLICY "Public update access" ON public.fund_master FOR UPDATE USING (true);
